sudo: required
dist: xenial
language: python
virtualenv:
  system_site_packages: true
python:
- '3.5'
install:
- pip install -r requirements.txt
- pip install coverage
- pip install codacy-coverage
script: pytest
after_script: cd ~
after_success:
  - coverage xml
  - python-codacy-coverage -r coverage.xml