env:
  global: 56435a01b3474518a03a65e74b4a4fb0
    - secure:
sudo: required
dist: xenial
language: python
virtualenv:
  system_site_packages: true
python:
- '3.5'
install:
- pip install -r requirements.txt
- pip install pytest
- pip install coverage
script: pytest
after_script: cd ~
after_success:
  - coverage run -m pytest
  - coverage xml -o coverage.xml
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Python -r coverage.xml --partial