language: python
python:
- '3.5'
- '3.6'
- '3.7'
install:
- pip install -r requirements.txt
- pwd
- pip freeze
- pip install pytest
- pip install coverage
script: python -m pytest tests --disable-warnings
after_success:
  - coverage run -m pytest tests
  - coverage xml -o coverage.xml
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Python -r coverage.xml --partial